### ISSUE TITLE
악덕사장 권지원을 고발합니다

### ISSUE THREAD

**Issue by iamfiro** [jwkwon0817/tapie-ssf-2024#2]
코드 수정이 필요해 PR을 남겼음에도 불구하고 직원을 폭행하고 협박 및 갈취를 하였습니다

평소해도 언행실이 불완전 하며 이거 완전 나쁜

**Comment by iamfiro** [comment]
@jwkwon0817

**Comment by iamfiro** [comment]
하 진자 어이업내

**Comment by iamfiro** [comment]
૮ ․ ․ ྀིა

**Comment by iamfiro** [comment]
໒꒰ྀི๑ ᷇ 𖥦 ᷆๑ ꒱ྀི১

**Comment by iamfiro** [comment]
⸜(*◉ ᴗ ◉)⸝

**Comment by h053698** [comment]
![image](https://github.com/user-attachments/assets/ff406a44-6f1b-4329-b546-70b1ac122056)

**Comment by shinleehyeon** [comment]
![image](https://github.com/user-attachments/assets/ef7930cf-2f7c-48b7-bb3b-28f8303a96c8)

**Comment by officeshinyujun** [comment]
악덕사장덜덜팁이

**Comment by haerin0303** [comment]
뭐노.

**Comment by iamfiro** [comment]
잘 해결했습니당 :)
